# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170702_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cached',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
