# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_city_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 2, 20, 21, 24, 813281, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
