# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_city_modified_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cached',
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(default=290),
        ),
        migrations.AddField(
            model_name='city',
            name='weather',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
