# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20170702_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='high_temperature_tomorrow',
            field=models.IntegerField(default=290),
        ),
        migrations.AddField(
            model_name='city',
            name='low_temperature_tomorrow',
            field=models.IntegerField(default=290),
        ),
    ]
